---

- name: firewalld systemd restart
  ansible.builtin.command: firewall-cmd --reload
  when: firewall_open_port == true
- name: systemd reload
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: restart prometheus
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: true
  delegate_to: "{{ prometheus_host }}"