--- 
- name: "install Prometheus"
  hosts: prometheus_servers
  become: true
  roles:
    - role: prometheus_server
      selinux_disable : true
      firewall_open_port : false
      prometheus_version : 2.54.1

- name: "install Node Exporter"
  hosts: node_exporter
  become: true
  roles:
    - role: node_exporter
      node_exporter_version : 1.8.2
      prometheus_host: '127.0.0.1'
      group_name: 'production'
      selinux_disable : true
      firewall_open_port : false
 
- name: "install ElasticSearch"
  hosts: elastic_search
  become: true
  roles:
    - role: elastic_search
      elastic_search_version: 8.9.2
      selinux_disable : true
      firewall_open_port : false
      elastic_password: elastik
      kibana_system_password: kibana


- name: "install Kibana"
  hosts: kibana
  become: true
  roles:
    - role: kibana
      kibana_version: 8.9.2
      selinux_disable : true
      firewall_open_port : false
      elasticsearch_user: "kibana_system"
      elasticsearch_password: "kibana"
      elasticsearch_host: '127.0.0.1'
      elasticsearch_port: '9200'

- name: "install FluentBit"
  hosts: fluent_bit
  become: true
  roles:
    - role: fluent_bit
      selinux_disable : true
      firewall_open_port : false
      elasticsearch_host: '127.0.0.1'
      elasticsearch_port: '9200'
