---

- name: Create directories for ElasticSearch
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - '/tmp/elasticsearch'

- name: Install Elastic apt sources
  apt_repository:
    repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
    state: present

- name: Debian - ElasticSearch is installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name: elasticsearch={{ elastic_search_version }}
  when: ansible_os_family == 'Debian'
  notify:
    - systemd reload

- name: Systemctl ElasticSearch Start
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes

- name: ElasticSearch Reset Password elastic
  ansible.builtin.command:
    cmd: printf 'y\n{{ elastic_password }}\n{{ elastic_password }}'| /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i

- name: ElasticSearch Reset Password kibana_system
  ansible.builtin.command:
    cmd: printf 'y\n{{ kibana_system_password }}\n{{ kibana_system_password }}'| /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -i


