---

- name: Create directories for Kibana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/kibana'

- name: Install Elastic apt sources
  apt_repository:
    repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
    state: present

- name: Debian - Kibana installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name: kibana
  when: ansible_os_family == 'Debian'
  notify:
    - systemd reload

- name: Systemctl Kibana Start
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes
