---

- name: Create directories for Kibana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/kibana'

- name: Install Kibana apt sources
  apt_repository:
    repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
    state: present

- name: Debian - Kibana installed
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name: kibana={{ kibana_version }}
  when: ansible_os_family == 'Debian'
  notify:
    - systemd reload

- name: Settings Kibana
  ansible.builtin.template:
    src: templates/kibana.yml
    dest: /etc/kibana/
    owner: root
    group: root

- name: Systemctl Kibana Start
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes
    
