---

- name: Create User prometheus
  ansible.builtin.user:
    name: prometheus
    create_home: no
    shell: /bin/false

- name: Create directories for prometheus
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/prometheus'
    - '/etc/prometheus'
    - '/etc/prometheus/prometheus.d'
    - '/var/lib/prometheus'

- name: Download And Unzipped Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus
    creates: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64
    remote_src: yes

- name: Copy Bin Files From Unzipped to Prometheus
  ansible.builtin.copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'prometheus', 'promtool' ]

- name: Copy Conf Files From Unzipped to Prometheus
  ansible.builtin.copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: /etc/prometheus/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'console_libraries', 'consoles' ]

- name: Copy Conf Files From Unzipped to Prometheus
  ansible.builtin.copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml
    dest: /etc/prometheus/prometheus.d/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus


- name: Create File for Prometheus Systemd
  ansible.builtin.template:
    src: templates/start_prometheus.sh
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: '0755'
  notify:
    - systemd reload

- name: Create File for Prometheus Systemd
  ansible.builtin.template:
    src: templates/prometheus.service
    dest: /etc/systemd/system/
    owner: root
    group: root
  notify:
    - systemd reload

- name: Systemctl Prometheus Start
  ansible.builtin.systemd_service:
    name: prometheus
    state: started
    enabled: yes